name: C++ test

on:
  push:
    paths:
      - "C*/**"
      - ".github/workflows/cpp_test.yml"
  pull_request:
    branches:
      - "*"

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: C++
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: |
          cmake .
          make
          ./logger_test

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: C++
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: |
          cmake -G "Unix Makefiles" .
          make
          echo "run tests :"
          .\logger_test.exe

  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: C++
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: |
          cmake .
          make
          ./logger_test
