name: Java test

on:
  push:
    paths:
      - "Java/**"
      - ".github/workflows/java.yml"
  pull_request:
    branches:
      - "*"

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Java
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Run test
        run: |
          javac -cp Logger_Java.jar: ./test/*.java
          java -cp Logger_Java.jar: test.Main

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Java
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Run test
        run: |
          javac -cp Logger_Java.jar .\test\*.java
          java test.Main -cp Logger_Java.jar:.

  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Java
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Run test
        run: |
          javac -cp Logger_Java.jar: ./test/*.java
          java -cp Logger_Java.jar: test.Main
