name: Java test

on:
  push:
    paths:
      - "Java/**"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Java
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: ./test/run.sh
