name: Kotlin test

on:
  push:
    paths:
      - "Kotlin/**"
      - ".github/workflows/kotlin.yml"
  pull_request:
    branches:
      - "*"

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Kotlin
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Run test
        run: ./test/run.sh

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Kotlin
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Run test
        run: .\test\run.bat

  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Kotlin
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Run test
        run: ./test/run.sh
